run_rust_dev:
	RUST_LOG=info cargo run
run_rust_release:
	RUST_LOG=info ./target/release/amazon_review_pipeline
clean_dirs:
	rm -rf datalayers/insights/toys_n_game/ && rm -rf datalayers/analytics/toys_n_game/
	